// =====================================================================================
// GENERATED FILE — DO NOT EDIT DIRECTLY
//
// Generated by: `cargo xtask generate`
// Inputs: `src/board.rs`, `src/app_composition.rs`, and reusable task modules
// =====================================================================================

#![no_main]
#![no_std]
#![forbid(unsafe_code)]
#![deny(warnings)]

mod prelude;

#[rtic::app(
    device = stm32f4xx_hal::pac,
    peripherals = true,
    dispatchers = [EXTI0, EXTI1]
)]
mod app {
    use crate::prelude::*;

    // Timing configuration generated from the board declaration.
    const SYSTEM_CLOCK_HZ: u32 = 168_000_000;

    systick_monotonic!(Mono, 1_000);

    #[shared]
    struct Shared {
        blink_enabled: bool,
        // ============================ Component `uart2` resources ============================
        uart2_rc_endpoint: Uart2Rx,
        uart2_rc_input: RcInputSnapshot,
        // ========================== End component `uart2` resources ==========================
        // ============================ Component `uart4` resources ============================
        uart4_comport_endpoint: Uart4Rx,
        uart4_rc_input: RcInputSnapshot,
        // ========================== End component `uart4` resources ==========================
    }

    #[local]
    struct Local {
        green_led: Pin<'B', 1, Output<PushPull>>,
        // ============================ Component `uart2` resources ============================
        uart2_consumer_state: SerialConsumer,
        // ========================== End component `uart2` resources ==========================
        // ============================ Component `uart4` resources ============================
        uart4_consumer_state: SerialConsumer,
        // ========================== End component `uart4` resources ==========================
    }

    #[init(local = [
        // ============================ Component `uart2` resources ============================
        uart2_rx_buffers: UartRxBufferBank =
            ferrowasp_stm32f4::app_storage::new_uart_rx_buffer_bank(),
        uart2_free_queue: UartRxFreeQueue = UartRxFreeQueue::new(),
        uart2_filled_queue: UartRxFilledQueue = UartRxFilledQueue::new(),
        // ========================== End component `uart2` resources ==========================
        // ============================ Component `uart4` resources ============================
        uart4_rx_buffers: UartRxBufferBank =
            ferrowasp_stm32f4::app_storage::new_uart_rx_buffer_bank(),
        uart4_free_queue: UartRxFreeQueue = UartRxFreeQueue::new(),
        uart4_filled_queue: UartRxFilledQueue = UartRxFilledQueue::new(),
        // ========================== End component `uart4` resources ==========================
    ])]
    fn init(cx: init::Context) -> (Shared, Local) {
        // =============================== System initialization ===============================
        let mut rcc = ferrowasp_stm32f4::clocks::freeze_hsi(
            cx.device.RCC.constrain(),
            SYSTEM_CLOCK_HZ,
            false,
        );
        Mono::start(cx.core.SYST, SYSTEM_CLOCK_HZ);
        let gpioa = cx.device.GPIOA.split(&mut rcc);
        let gpiob = cx.device.GPIOB.split(&mut rcc);
        // ============================= End system initialization =============================

        // ----------------------------- Task `blink_led` ------------------------------
        let mut green_led = gpiob.pb1.into_push_pull_output_in_state(PinState::Low);
        green_led.set_internal_resistor(Pull::None);
        green_led.set_speed(Speed::Low);
        // --------------------------- End task `blink_led` ----------------------------

        // ================================= Component `uart2` =================================
        let dma1 = StreamsTuple::new(cx.device.DMA1, &mut rcc);
        let uart2_rc_endpoint = ferrowasp_stm32f4::uart_dma::init_usart2_rx_only(
            Usart2RxOnlyResources {
                rx_pin: gpioa.pa3,
                usart: cx.device.USART2,
                rx_dma: dma1.5,
            },
            &mut rcc,
            SerialProtocol::Sbus,
            UartRxStorageResources {
                buffers: cx.local.uart2_rx_buffers,
                free_queue: cx.local.uart2_free_queue,
                filled_queue: cx.local.uart2_filled_queue,
            },
        );
        // =============================== End component `uart2` ===============================

        // ================================= Component `uart4` =================================
        let uart4_comport_endpoint = ferrowasp_stm32f4::uart_dma::init_uart4_rx_only(
            Uart4RxOnlyResources {
                rx_pin: gpioa.pa1,
                uart: cx.device.UART4,
                rx_dma: dma1.2,
            },
            &mut rcc,
            SerialProtocol::Raw,
            UartRxStorageResources {
                buffers: cx.local.uart4_rx_buffers,
                free_queue: cx.local.uart4_free_queue,
                filled_queue: cx.local.uart4_filled_queue,
            },
        );
        // =============================== End component `uart4` ===============================

        // =============================== Initial task startup ================================

        // Task `blink_led`
        blink_led::spawn().expect("init must spawn declared task blink_led");

        // Task `rc_heartbeat`
        rc_heartbeat::spawn().expect("init must spawn declared task rc_heartbeat");

        // Component `uart2` task `uart2_consumer`
        uart2_consumer::spawn().expect("init must spawn declared task uart2_consumer");

        // Component `uart4` task `uart4_consumer`
        uart4_consumer::spawn().expect("init must spawn declared task uart4_consumer");

        (
            Shared {
                blink_enabled: true,
                // ============================ Component `uart2` resources ============================
                uart2_rc_endpoint,
                uart2_rc_input: RcInputSnapshot::new(),
                // ========================== End component `uart2` resources ==========================
                // ============================ Component `uart4` resources ============================
                uart4_comport_endpoint,
                uart4_rc_input: RcInputSnapshot::new(),
                // ========================== End component `uart4` resources ==========================
            },
            Local {
                green_led,
                // ============================ Component `uart2` resources ============================
                uart2_consumer_state: SerialConsumer::new(SerialPortAssignment::Rc(
                    RcProtocol::Sbus,
                )),
                // ========================== End component `uart2` resources ==========================
                // ============================ Component `uart4` resources ============================
                uart4_consumer_state: SerialConsumer::new(SerialPortAssignment::ComPort),
                // ========================== End component `uart4` resources ==========================
            },
        )
    }

    #[task(priority = 1, local = [green_led], shared = [blink_enabled])]
    async fn blink_led(mut cx: blink_led::Context) {
        const TOGGLE_INTERVAL_MS: u32 = 1_000;

        let mut blink_count = 0_u32;
        loop {
            Mono::delay(TOGGLE_INTERVAL_MS.millis()).await;
            let enabled = cx.shared.blink_enabled.lock(|enabled| *enabled);
            if enabled {
                let _ = StatefulOutputPin::toggle(cx.local.green_led);
                blink_count = blink_count.wrapping_add(1);
                report_blink::spawn(blink_count)
                    .expect("blink report task queue must have capacity");
            } else {
                let _ = OutputPin::set_low(cx.local.green_led);
            }
        }
    }

    #[task(priority = 1)]
    async fn report_blink(cx: report_blink::Context, count: u32) {
        let _ = cx;
        defmt::info!("Blink {}", count);
    }

    #[task(priority = 1, shared = [uart2_rc_input])]
    async fn rc_heartbeat(mut cx: rc_heartbeat::Context) {
        const REPORT_INTERVAL_MS: u32 = 1_000;

        loop {
            Mono::delay(REPORT_INTERVAL_MS.millis()).await;
            let snapshot = cx.shared.uart2_rc_input.lock(|snapshot| *snapshot);
            if snapshot.has_valid_frame {
                defmt::info!(
                    "RC channels: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}], d1={}, d2={}, frame_lost={}, failsafe={}, valid={}, errors={}",
                    snapshot.channels[0],
                    snapshot.channels[1],
                    snapshot.channels[2],
                    snapshot.channels[3],
                    snapshot.channels[4],
                    snapshot.channels[5],
                    snapshot.channels[6],
                    snapshot.channels[7],
                    snapshot.channels[8],
                    snapshot.channels[9],
                    snapshot.channels[10],
                    snapshot.channels[11],
                    snapshot.channels[12],
                    snapshot.channels[13],
                    snapshot.channels[14],
                    snapshot.channels[15],
                    snapshot.digital_channel_1,
                    snapshot.digital_channel_2,
                    snapshot.frame_lost,
                    snapshot.failsafe,
                    snapshot.valid_frames,
                    snapshot.parse_errors,
                );
            } else {
                defmt::info!(
                    "RC heartbeat: no RC frame (errors={})",
                    snapshot.parse_errors
                );
            }
        }
    }

    // ============================== Component `uart2` tasks ==============================
    #[task(binds = DMA1_STREAM5, priority = 3, shared = [uart2_rc_endpoint])]
    fn uart2_dma_irq(mut cx: uart2_dma_irq::Context) {
        match cx.shared.uart2_rc_endpoint.lock(|rx| rx.service_dma_irq()) {
            UartRxIrqOutcome::Ignored | UartRxIrqOutcome::Delivered | UartRxIrqOutcome::NoChunk => {
            }
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX DMA error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX DMA buffer delivery error")
            }
        }
    }

    #[task(binds = USART2, priority = 3, shared = [uart2_rc_endpoint])]
    fn uart2_idle_irq(mut cx: uart2_idle_irq::Context) {
        match cx.shared.uart2_rc_endpoint.lock(|rx| rx.service_idle_irq()) {
            UartRxIrqOutcome::Ignored | UartRxIrqOutcome::Delivered | UartRxIrqOutcome::NoChunk => {
            }
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX peripheral error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX IDLE buffer delivery error")
            }
        }
    }

    #[task(
        priority = 2,
        local = [uart2_consumer_state],
        shared = [uart2_rc_endpoint, uart2_rc_input]
    )]
    async fn uart2_consumer(mut cx: uart2_consumer::Context) {
        let mut bytes = [0_u8; UART_RX_BUFFER_SIZE];

        loop {
            match cx
                .shared
                .uart2_rc_endpoint
                .lock(|endpoint| endpoint.read_chunk(&mut bytes))
            {
                UartRxReadOutcome::NoChunk => {}
                UartRxReadOutcome::RecycleError => {
                    defmt::warn!("UART RX buffer recycle error");
                }
                UartRxReadOutcome::Chunk(len) => {
                    cx.local
                        .uart2_consumer_state
                        .consume(&bytes[..len], |event| match event {
                            SerialConsumerEvent::RcSnapshot(snapshot) => {
                                cx.shared.uart2_rc_input.lock(|output| *output = snapshot);
                            }
                            SerialConsumerEvent::ComPortLine(line) => {
                                match core::str::from_utf8(line.as_slice()) {
                                    Ok(line) => defmt::info!("COMPORT: {}", line),
                                    Err(_) => {
                                        defmt::info!("COMPORT bytes: {=[u8]}", line.as_slice())
                                    }
                                }
                            }
                            SerialConsumerEvent::ComPortOverflow => {
                                defmt::warn!("COMPORT line exceeded 64 bytes; discarded");
                            }
                        });
                }
            }

            Mono::delay(1.millis()).await;
        }
    }
    // ============================ End component `uart2` tasks ============================

    // ============================== Component `uart4` tasks ==============================
    #[task(binds = DMA1_STREAM2, priority = 3, shared = [uart4_comport_endpoint])]
    fn uart4_dma_irq(mut cx: uart4_dma_irq::Context) {
        match cx
            .shared
            .uart4_comport_endpoint
            .lock(|rx| rx.service_dma_irq())
        {
            UartRxIrqOutcome::Ignored | UartRxIrqOutcome::Delivered | UartRxIrqOutcome::NoChunk => {
            }
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX DMA error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX DMA buffer delivery error")
            }
        }
    }

    #[task(binds = UART4, priority = 3, shared = [uart4_comport_endpoint])]
    fn uart4_idle_irq(mut cx: uart4_idle_irq::Context) {
        match cx
            .shared
            .uart4_comport_endpoint
            .lock(|rx| rx.service_idle_irq())
        {
            UartRxIrqOutcome::Ignored | UartRxIrqOutcome::Delivered | UartRxIrqOutcome::NoChunk => {
            }
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX peripheral error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX IDLE buffer delivery error")
            }
        }
    }

    #[task(
        priority = 2,
        local = [uart4_consumer_state],
        shared = [uart4_comport_endpoint, uart4_rc_input]
    )]
    async fn uart4_consumer(mut cx: uart4_consumer::Context) {
        let mut bytes = [0_u8; UART_RX_BUFFER_SIZE];

        loop {
            match cx
                .shared
                .uart4_comport_endpoint
                .lock(|endpoint| endpoint.read_chunk(&mut bytes))
            {
                UartRxReadOutcome::NoChunk => {}
                UartRxReadOutcome::RecycleError => {
                    defmt::warn!("UART RX buffer recycle error");
                }
                UartRxReadOutcome::Chunk(len) => {
                    cx.local
                        .uart4_consumer_state
                        .consume(&bytes[..len], |event| match event {
                            SerialConsumerEvent::RcSnapshot(snapshot) => {
                                cx.shared.uart4_rc_input.lock(|output| *output = snapshot);
                            }
                            SerialConsumerEvent::ComPortLine(line) => {
                                match core::str::from_utf8(line.as_slice()) {
                                    Ok(line) => defmt::info!("COMPORT: {}", line),
                                    Err(_) => {
                                        defmt::info!("COMPORT bytes: {=[u8]}", line.as_slice())
                                    }
                                }
                            }
                            SerialConsumerEvent::ComPortOverflow => {
                                defmt::warn!("COMPORT line exceeded 64 bytes; discarded");
                            }
                        });
                }
            }

            Mono::delay(1.millis()).await;
        }
    }
    // ============================ End component `uart4` tasks ============================
}
