// =====================================================================================
// GENERATED FILE — DO NOT EDIT DIRECTLY
//
// Generated by: `cargo xtask generate`
// Inputs: `src/board.rs`, `src/app_composition.rs`, and reusable task modules
// =====================================================================================

//! Imports selected for the generated RTIC application.

// Firmware runtime handlers.
use defmt_rtt as _;
use panic_halt as _;

// Application-facing imports selected from the resolved application.
pub(crate) use ferrowasp_drivers::serial_consumer::{SerialConsumer, SerialConsumerEvent};
pub(crate) use ferrowasp_io_core::digital::prelude::{OutputPin, StatefulOutputPin};
pub(crate) use ferrowasp_io_core::serial::RcInputSnapshot;
pub(crate) use ferrowasp_io_core::serial::RcProtocol;
pub(crate) use ferrowasp_io_core::serial::SerialPortAssignment;
pub(crate) use ferrowasp_io_core::serial::SerialProtocol;
pub(crate) use ferrowasp_stm32f4::rtic::hal as stm32f4xx_hal;
pub(crate) use ferrowasp_stm32f4::rtic::prelude::*;
pub(crate) use ferrowasp_stm32f4::{
    app_storage::{UartRxBufferBank, UartRxFilledQueue, UartRxFreeQueue, UartRxStorageResources},
    uart_dma::{
        UART_RX_BUFFER_SIZE, Uart2Rx, Uart4Rx, Uart4RxOnlyResources, UartRxIrqOutcome,
        UartRxReadOutcome, Usart2RxOnlyResources,
    },
};
