// =====================================================================================
// GENERATED FILE — DO NOT EDIT DIRECTLY
//
// Generated by: `cargo xtask generate`
// Inputs: `src/board.rs`, `src/app_composition.rs`, and reusable task modules
// =====================================================================================

//! Imports selected for the generated RTIC application.

// Firmware runtime handlers.
use defmt_rtt as _;
use panic_halt as _;

// Application-facing imports selected from the resolved application.
{{PRELUDE_EXPORTS}}
