// =====================================================================================
// GENERATED FILE — DO NOT EDIT DIRECTLY
//
// Generated by: `cargo xtask generate`
// Inputs: `src/board.rs`, `src/app_composition.rs`, and reusable task modules
// =====================================================================================

#![no_main]
#![no_std]
#![forbid(unsafe_code)]
#![deny(warnings)]

mod prelude;

#[rtic::app(
    device = stm32f4xx_hal::pac,
    peripherals = true,
    dispatchers = [EXTI0, EXTI1]
)]
mod app {
    use crate::prelude::*;

    // Timing configuration generated from the board declaration.
    const SYSTEM_CLOCK_HZ: u32 = 168_000_000;

    systick_monotonic!(Mono, 1_000);

    #[shared]
    struct Shared {
        // ============================ Component `uart2` resources ============================
        uart2: Uart2RxIrq,
        uart2_rx: UartRxParserSide,
        // ========================== End component `uart2` resources ==========================
        // ======================== Component `command_input` resources ========================
        command_input_rc_input_reader: ObserverReader<'static, RcInputSnapshot>,
        // ====================== End component `command_input` resources ======================
    }

    #[local]
    struct Local {
        // ======================== Component `command_input` resources ========================
        command_input_decoder: SbusConsumer,
        command_input_rc_input_publisher: ObserverPublisher<'static, RcInputSnapshot>,
        // ====================== End component `command_input` resources ======================
    }

    #[init(local = [
        // ============================ Component `uart2` resources ============================
        uart2_rx_buffers: UartRxBufferBank =
            ferrowasp_stm32f4::app_storage::new_uart_rx_buffer_bank(),
        uart2_free_queue: UartRxFreeQueue = UartRxFreeQueue::new(),
        uart2_filled_queue: UartRxFilledQueue = UartRxFilledQueue::new(),
        // ========================== End component `uart2` resources ==========================
        // ======================== Component `command_input` resources ========================
        command_input_rc_input_channel: ObserverChannel<RcInputSnapshot> =
            ObserverChannel::new(),
        // ====================== End component `command_input` resources ======================
    ])]
    fn init(cx: init::Context) -> (Shared, Local) {
        // =============================== System initialization ===============================
        let mut rcc =
            ferrowasp_stm32f4::clocks::freeze_hse(cx.device.RCC.constrain(), 8_000_000, SYSTEM_CLOCK_HZ, true);
        Mono::start(cx.core.SYST, SYSTEM_CLOCK_HZ);
        let gpioa = cx.device.GPIOA.split(&mut rcc);
        // ============================= End system initialization =============================

        // ================================= Component `uart2` =================================
        let dma1 = StreamsTuple::new(cx.device.DMA1, &mut rcc);
        let uart2_parts = ferrowasp_stm32f4::uart_dma::init_usart2_rx_only(
            Usart2RxOnlyResources {
                rx_pin: gpioa.pa3,
                usart: cx.device.USART2,
                rx_dma: dma1.5,
            },
            &mut rcc,
            SerialProtocol::Sbus,
            UartRxStorageResources {
                buffers: cx.local.uart2_rx_buffers,
                free_queue: cx.local.uart2_free_queue,
                filled_queue: cx.local.uart2_filled_queue,
            },
        );
        let uart2 = uart2_parts.irq;
        let uart2_rx = uart2_parts.parser;
        // =============================== End component `uart2` ===============================

        // ============================= Component `command_input` =============================
        let (command_input_rc_input_publisher, command_input_rc_input_reader) =
            cx.local.command_input_rc_input_channel.split();
        // =========================== End component `command_input` ===========================

        // =============================== Initial task startup ================================

        // Task `rc_heartbeat`
        rc_heartbeat::spawn().expect("init must spawn declared task rc_heartbeat");

        // Component `command_input` task `command_input_consumer`
        command_input_consumer::spawn().expect("init must spawn declared task command_input_consumer");

        (Shared {
            // ============================ Component `uart2` resources ============================
            uart2,
            uart2_rx: uart2_rx,
            // ========================== End component `uart2` resources ==========================
            // ======================== Component `command_input` resources ========================
            command_input_rc_input_reader: command_input_rc_input_reader,
            // ====================== End component `command_input` resources ======================
        }, Local {
            // ======================== Component `command_input` resources ========================
            command_input_decoder: SbusConsumer::new(),
            command_input_rc_input_publisher: command_input_rc_input_publisher,
            // ====================== End component `command_input` resources ======================
        })
    }

    #[task(priority = 1, shared = [command_input_rc_input_reader])]
    async fn rc_heartbeat(mut cx: rc_heartbeat::Context) {
        const REPORT_INTERVAL_MS: u32 = 1_000;

        loop {
            Mono::delay(REPORT_INTERVAL_MS.millis()).await;
            let snapshot = cx.shared.command_input_rc_input_reader.lock(|reader| reader.latest());
            match snapshot {
                Some(snapshot) if snapshot.has_valid_frame => {
                    defmt::info!(
                        "RC channels: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}], d1={}, d2={}, frame_lost={}, failsafe={}, valid={}, errors={}",
                        snapshot.channels[0], snapshot.channels[1], snapshot.channels[2],
                        snapshot.channels[3], snapshot.channels[4], snapshot.channels[5],
                        snapshot.channels[6], snapshot.channels[7], snapshot.channels[8],
                        snapshot.channels[9], snapshot.channels[10], snapshot.channels[11],
                        snapshot.channels[12], snapshot.channels[13], snapshot.channels[14],
                        snapshot.channels[15], snapshot.digital_channel_1,
                        snapshot.digital_channel_2, snapshot.frame_lost, snapshot.failsafe,
                        snapshot.valid_frames, snapshot.parse_errors,
                    );
                }
                Some(snapshot) => {
                    defmt::info!("RC heartbeat: no RC frame (errors={})", snapshot.parse_errors);
                }
                None => {
                    defmt::info!("RC heartbeat: no RC frame (errors=0)");
                }
            }
        }
    }

    // ============================== Component `uart2` tasks ==============================
    #[task(binds = DMA1_STREAM5, priority = 3, shared = [uart2])]
    fn uart2_dma_irq(mut cx: uart2_dma_irq::Context) {
        match cx.shared.uart2.lock(|rx| rx.service_dma_irq()) {
            UartRxIrqOutcome::Ignored
            | UartRxIrqOutcome::Delivered
            | UartRxIrqOutcome::NoChunk => {}
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX DMA error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX DMA buffer delivery error")
            }
        }
    }

    #[task(binds = USART2, priority = 3, shared = [uart2])]
    fn uart2_idle_irq(mut cx: uart2_idle_irq::Context) {
        match cx.shared.uart2.lock(|rx| rx.service_idle_irq()) {
            UartRxIrqOutcome::Ignored
            | UartRxIrqOutcome::Delivered
            | UartRxIrqOutcome::NoChunk => {}
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX peripheral error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX IDLE buffer delivery error")
            }
        }
    }
    // ============================ End component `uart2` tasks ============================

    // ========================== Component `command_input` tasks ==========================
    #[task(
        priority = 2,
        local = [command_input_decoder, command_input_rc_input_publisher],
        shared = [uart2_rx]
    )]
    async fn command_input_consumer(mut cx: command_input_consumer::Context) {
        let mut bytes = [0_u8; UART_RX_BUFFER_SIZE];

        loop {
            match cx.shared.uart2_rx.lock(|rx| rx.read_chunk(&mut bytes)) {
                UartRxReadOutcome::NoChunk => {}
                UartRxReadOutcome::RecycleError => {
                    defmt::warn!("serial RX buffer recycle error");
                }
                UartRxReadOutcome::Chunk(len) => {
                    cx.local.command_input_decoder.consume(&bytes[..len], |snapshot| {
                        cx.local.command_input_rc_input_publisher.publish(snapshot);
                    });
                }
            }

            Mono::delay(1.millis()).await;
        }
    }
    // ======================== End component `command_input` tasks ========================
}
