[package]
name = "ferrowasp-bsp"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
path = "src/lib.rs"

[features]
default = []
ferrowasp-fcu3 = [
    "dep:ferrowasp-drivers",
    "dep:ferrowasp-mspv1",
    "dep:ferrowasp-stm32f4",
]
ferrowasp-fcu3-dshot-four = [
    "ferrowasp-fcu3",
    "ferrowasp-stm32f4/dshot",
]
foxeer-f405-v2 = [
    "dep:ferrowasp-drivers",
    "dep:ferrowasp-mspv1",
    "dep:ferrowasp-stm32f4",
]
nucleo-f401re = ["dep:stm32f4xx-hal"]

[dependencies]
ferrowasp-core = { path = "../ferrowasp-core" }
ferrowasp-io-core = { path = "../ferrowasp-io-core" }

[target.'cfg(target_arch = "arm")'.dependencies]
ferrowasp-drivers = { path = "../ferrowasp-drivers", optional = true }
ferrowasp-mspv1 = { path = "../ferrowasp-mspv1", optional = true }
ferrowasp-stm32f4 = { path = "../ferrowasp-stm32f4", optional = true }
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal.git", rev = "78d79609137d5c380320f7bf1a9120967babc61d", features = ["stm32f401"], optional = true }
