// =====================================================================================
// GENERATED FILE — DO NOT EDIT DIRECTLY
//
// Generated by: `cargo xtask generate`
// Inputs: `src/board.rs`, `src/app_composition.rs`, and reusable task modules
// =====================================================================================

#![no_main]
#![no_std]
#![forbid(unsafe_code)]
#![deny(warnings)]

mod prelude;

#[rtic::app(
    device = stm32f4xx_hal::pac,
    peripherals = true,
    dispatchers = [EXTI0, EXTI1]
)]
mod app {
    use crate::prelude::*;

    // Timing configuration generated from the board declaration.
    const SYSTEM_CLOCK_HZ: u32 = 84_000_000;

    systick_monotonic!(Mono, 1_000);

    #[shared]
    struct Shared {
        blink_enabled: bool,
        // ============================ Component `uart2` resources ============================
        uart2: Uart2RxIrq,
        uart2_rx: UartRxParserSide,
        // ========================== End component `uart2` resources ==========================
    }

    #[local]
    struct Local {
        led3: Pin<'A', 5, Output<PushPull>>,
        user_button: Pin<'C', 13, Input>,
        // =========================== Component `comport` resources ===========================
        comport_decoder: LineConsumer,
        // ========================= End component `comport` resources =========================
    }

    #[init(local = [
        // ============================ Component `uart2` resources ============================
        uart2_rx_buffers: UartRxBufferBank =
            ferrowasp_stm32f4::app_storage::new_uart_rx_buffer_bank(),
        uart2_free_queue: UartRxFreeQueue = UartRxFreeQueue::new(),
        uart2_filled_queue: UartRxFilledQueue = UartRxFilledQueue::new(),
        // ========================== End component `uart2` resources ==========================
    ])]
    fn init(cx: init::Context) -> (Shared, Local) {
        // =============================== System initialization ===============================
        let mut rcc =
            ferrowasp_stm32f4::clocks::freeze_hsi(cx.device.RCC.constrain(), SYSTEM_CLOCK_HZ, false);
        Mono::start(cx.core.SYST, SYSTEM_CLOCK_HZ);
        let gpioa = cx.device.GPIOA.split(&mut rcc);
        let gpioc = cx.device.GPIOC.split(&mut rcc);
        let mut syscfg = cx.device.SYSCFG.constrain(&mut rcc);
        let mut exti = cx.device.EXTI;
        // ============================= End system initialization =============================

        // ----------------------------- Task `blink_led` ------------------------------
        let mut led3 = gpioa.pa5.into_push_pull_output_in_state(PinState::Low);
        led3.set_internal_resistor(Pull::None);
        led3.set_speed(Speed::Low);
        // --------------------------- End task `blink_led` ----------------------------

        // ---------------------------- Task `button_exti` -----------------------------
        let user_button = Input::new(gpioc.pc13, Pull::Up);
        let user_button = ferrowasp_stm32f4::exti::init_input(user_button, &mut syscfg, &mut exti, Edge::Falling);
        // -------------------------- End task `button_exti` ---------------------------

        // ================================= Component `uart2` =================================
        let dma1 = StreamsTuple::new(cx.device.DMA1, &mut rcc);
        let uart2_parts = ferrowasp_stm32f4::uart_dma::init_usart2_rx_only(
            Usart2RxOnlyResources {
                rx_pin: gpioa.pa3,
                usart: cx.device.USART2,
                rx_dma: dma1.5,
            },
            &mut rcc,
            SerialProtocol::Raw,
            UartRxStorageResources {
                buffers: cx.local.uart2_rx_buffers,
                free_queue: cx.local.uart2_free_queue,
                filled_queue: cx.local.uart2_filled_queue,
            },
        );
        let uart2 = uart2_parts.irq;
        let uart2_rx = uart2_parts.parser;
        // =============================== End component `uart2` ===============================

        // =============================== Initial task startup ================================

        // Task `blink_led`
        blink_led::spawn().expect("init must spawn declared task blink_led");

        // Component `comport` task `comport_consumer`
        comport_consumer::spawn().expect("init must spawn declared task comport_consumer");

        (Shared {
            blink_enabled: true,
            // ============================ Component `uart2` resources ============================
            uart2,
            uart2_rx: uart2_rx,
            // ========================== End component `uart2` resources ==========================
        }, Local {
            led3,
            user_button,
            // =========================== Component `comport` resources ===========================
            comport_decoder: LineConsumer::new(),
            // ========================= End component `comport` resources =========================
        })
    }

    #[task(priority = 1, local = [led3], shared = [blink_enabled])]
    async fn blink_led(mut cx: blink_led::Context) {
        const TOGGLE_INTERVAL_MS: u32 = 1_000;

        let mut blink_count = 0_u32;
        loop {
            Mono::delay(TOGGLE_INTERVAL_MS.millis()).await;
            let enabled = cx.shared.blink_enabled.lock(|enabled| *enabled);
            if enabled {
                let _ = StatefulOutputPin::toggle(cx.local.led3);
                blink_count = blink_count.wrapping_add(1);
                report_blink::spawn(blink_count)
                    .expect("blink report task queue must have capacity");
            } else {
                let _ = OutputPin::set_low(cx.local.led3);
            }
        }
    }

    #[task(priority = 1)]
    async fn report_blink(cx: report_blink::Context, count: u32) {
        let _ = cx;
        defmt::info!("Blink {}", count);
    }

    #[task(
        binds = EXTI15_10,
        priority = 2,
        local = [user_button],
        shared = [blink_enabled]
    )]
    fn button_exti(mut cx: button_exti::Context) {
        cx.local.user_button.clear_interrupt_pending_bit();
        let enabled = cx.shared.blink_enabled.lock(|enabled| {
            *enabled = !*enabled;
            *enabled
        });
        defmt::info!("Blink enabled: {}", enabled);
    }

    // ============================== Component `uart2` tasks ==============================
    #[task(binds = DMA1_STREAM5, priority = 3, shared = [uart2])]
    fn uart2_dma_irq(mut cx: uart2_dma_irq::Context) {
        match cx.shared.uart2.lock(|rx| rx.service_dma_irq()) {
            UartRxIrqOutcome::Ignored
            | UartRxIrqOutcome::Delivered
            | UartRxIrqOutcome::NoChunk => {}
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX DMA error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX DMA buffer delivery error")
            }
        }
    }

    #[task(binds = USART2, priority = 3, shared = [uart2])]
    fn uart2_idle_irq(mut cx: uart2_idle_irq::Context) {
        match cx.shared.uart2.lock(|rx| rx.service_idle_irq()) {
            UartRxIrqOutcome::Ignored
            | UartRxIrqOutcome::Delivered
            | UartRxIrqOutcome::NoChunk => {}
            UartRxIrqOutcome::DmaError => defmt::warn!("UART RX peripheral error"),
            UartRxIrqOutcome::DeliveryError(_) => {
                defmt::warn!("UART RX IDLE buffer delivery error")
            }
        }
    }
    // ============================ End component `uart2` tasks ============================

    // ============================= Component `comport` tasks =============================
    #[task(priority = 2, local = [comport_decoder], shared = [uart2_rx])]
    async fn comport_consumer(mut cx: comport_consumer::Context) {
        let mut bytes = [0_u8; UART_RX_BUFFER_SIZE];

        loop {
            match cx.shared.uart2_rx.lock(|rx| rx.read_chunk(&mut bytes)) {
                UartRxReadOutcome::NoChunk => {}
                UartRxReadOutcome::RecycleError => {
                    defmt::warn!("serial RX buffer recycle error");
                }
                UartRxReadOutcome::Chunk(len) => {
                    cx.local.comport_decoder.consume(&bytes[..len], |event| match event {
                        LineConsumerEvent::Line(line) => {
                            match core::str::from_utf8(line.as_slice()) {
                                Ok(line) => defmt::info!("COMPORT: {}", line),
                                Err(_) => defmt::info!("COMPORT bytes: {=[u8]}", line.as_slice()),
                            }
                        }
                        LineConsumerEvent::Overflow => {
                            defmt::warn!("COMPORT line exceeded 64 bytes; discarded");
                        }
                    });
                }
            }

            Mono::delay(1.millis()).await;
        }
    }
    // =========================== End component `comport` tasks ===========================
}
