// =====================================================================================
// GENERATED FILE — DO NOT EDIT DIRECTLY
//
// Generated by: `cargo xtask generate`
// Inputs: `src/board.rs`, `src/app_composition.rs`, and reusable task modules
// =====================================================================================

#![no_main]
#![no_std]
#![forbid(unsafe_code)]
#![deny(warnings)]

mod prelude;

#[rtic::app(
    device = stm32f4xx_hal::pac,
    peripherals = true,
    dispatchers = [{{DISPATCHERS}}]
)]
mod app {
    {{PRELUDE_IMPORT}}

    {{TIMING_DECLARATIONS}}

    #[shared]
    {{SHARED_STRUCT}}

    #[local]
    {{LOCAL_STRUCT}}

    {{INIT_ATTRIBUTE}}
    fn init(cx: init::Context) -> (Shared, Local) {
        {{BOARD_INIT}}

        {{INIT_SPAWNS}}

        ({{SHARED_VALUE}}, {{LOCAL_VALUE}})
    }

    {{TASKS}}
}
