[package]
name = "ferrowasp-drivers"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
embedded-hal = { workspace = true }
defmt = { version = "1.0.1", optional = true }
ferrowasp-io-core = { path = "../ferrowasp-io-core" }
heapless = { workspace = true }
sbus-rs = { version = "=0.1.3", default-features = false }

[features]
default = []
defmt = ["dep:defmt"]
