[package]
name = "ferrowasp-stm32f4"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
path = "src/lib.rs"

[features]
default = []
bench_spi_timeout_recovery = []
dshot = ["dep:ferrowasp-waveform"]

[dependencies]
embedded-hal = { workspace = true }
ferrowasp-io-core = { path = "../ferrowasp-io-core" }
ferrowasp-waveform = { path = "../ferrowasp-waveform", optional = true }
heapless = { workspace = true }
rc-pwm = { path = "../rc-pwm" }

[target.'cfg(target_arch = "arm")'.dependencies]
stm32f4xx-hal = { git = "https://github.com/stm32-rs/stm32f4xx-hal.git", rev = "78d79609137d5c380320f7bf1a9120967babc61d", features = ["stm32f405", "rtic2", "defmt", "usb_fs", "uart4"] }
