{{SERIAL_RESOURCE}}: SerialRxTx<{{BUFFER_SIZE}}, {{RX_QUEUE_CAPACITY}}, {{TX_QUEUE_CAPACITY}}>,
{{RX_DMA_RESOURCE}}: Usart1RxDma<{{BUFFER_SIZE}}>,
{{TX_DMA_RESOURCE}}: Usart1TxDma<{{BUFFER_SIZE}}>,
{{OSD_TELEMETRY_RESOURCE}}: OsdTelemetryState,
