[package]
name = "app-builder-v2-nucleo-f401re"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false
build = "build.rs"

[workspace]
resolver = "2"

[[bin]]
name = "handwritten"
path = "handwritten/src/main.rs"
test = false
bench = false

[[bin]]
name = "generated"
path = "generated/src/main.rs"
test = false
bench = false

[dependencies]
panic-halt = "=1.0.0"
ferrowasp-stm32f4 = { path = "../../../crates/ferrowasp-stm32f4", features = ["stm32f401"] }
rtic = { version = "=2.3.0", features = ["thumbv7-backend"] }

[profile.dev.package."*"]
opt-level = "s"

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
debug = 2
incremental = false
lto = true
opt-level = "s"
panic = "abort"
